### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by Litarvan**
Fixed Windows bugs

### CODE REVIEW

**Comment by jamierocks** [comment]
The problem with this is that the mappings can't be taken from a linux system and used on a windows system, etc

**Comment by jamierocks** [comment]
To give more insight on this - I am using the standard set by mercurial's patches (see [here](https://github.com/cloudbees/diff4j/blob/69289a936ae71e66c0f3a86242f784846cb75ef1/src/main/java/com/cloudbees/diff/ContextualPatch.java#L592)), so the fact isn't working on Windows is strange :s

**Comment by Litarvan** [comment]
What ? I don't understand, what is the problems ? I just modified / in \ and /dev/null to C:\nul
This doesn't affect the .patch files O_o

**Comment by jamierocks** [comment]
/dev/null is a placeholder for diff4j, it has to be the same for all operating systems. But to also answer `This doesn't affect the .patch files` - it does lets say a patch was made on windows it would have C:/nul and diff4j wouldn't read it properly

**Comment by Litarvan** [comment]
Ok but, actually, it is just not working on Windows ._. i think it is better to fix this

**Comment by jamierocks** [comment]
This pr in its current state doesn't actually fix the issue. I'm about to clone one of my projects using ProPatches and test this on Windows.

**Comment by jamierocks** [comment]
Try release 1.2.1 https://github.com/jamierocks/ProPatcher/commit/b02caa374320d3530f75a6291b00a3271988c7f5

**Comment by Litarvan** [comment]
Missing the File.separator fix (look at my commit)

**Comment by jamierocks** [comment]
If you can try out the File.separator fix on Windows to generate a patch file and Gist the patch file showing it works as expected then I'll include it.

**Comment by Litarvan** [comment]
I would not post a pull request without testing ^^ (Using my 1.2.0 fork, on Windows 10) : https://gist.github.com/Litarvan/c9edd6db973227b8bcbe8ed74438dc03

**Comment by jamierocks** [comment]
Merged with https://github.com/jamierocks/ProPatcher/commit/06d2bdd210e3ac0afda33a10155e9ae6422c87c4
In release 1.2.2 ;)

**Comment by Litarvan** [comment]
Thanks a lot ! Your plugin will be a lot useful for me and my friends !

**Comment by jamierocks** [comment]
No problem - Glad to be of help ;)

**Pull request closed without merging**
